### ISSUE TITLE
JDBC, persistence and statistics

### ISSUE THREAD

**Issue by keriks99** [OxalisCommunity/oxalis#309]
We are running Oxalis 4.0.0.RC3, and are able to send both inbound and outbound messages using oxalis-standalone. The inbound files are stored in /var/peppol/IN, but we don't see anything stored in our database, and the http://localhost:8080/oxalis/statistics returns 404 Not Found. 

We have set up mysql and created the 5 tables according to the .sql-script. 

Below is the content of our oxalis.conf. 

How do we get the persistence to the database and the statistics to work?

```
oxalis.keystore {
path=oxalis-keystore.jks
password = myPassword
key.alias = myAlias
key.password = myPassword 
}
oxalis.database.datasource = dbcp
oxalis.database.dbcp.validation = select 1

oxalis.database.driver.class = com.mysql.jdbc.Driver
oxalis.database.driver.path = "file:///usr/share/java/mysql-connector-java.jar"
oxalis.database.jdbc.connection = "jdbc:mysql://mysqlHost:3306/oxalis"
oxalis.database.jdbc.username = oxalis
oxalis.database.jdbc.password = myPassword

oxalis.pki.version=V2

# The relative name of the directory holding plugin
oxalis.path.plugin = oxalis-plugin

oxalis.path.conf = ""

# Signals to Oxalis that we should look for plugin
oxalis.persister.receipt = plugin
#oxalis.persister.payload = plugin

# Where to store inbound files
oxalis.path.inbound = /var/peppol/IN

#oxalis.persister.payload = "file:///software/git/oxalis/oxalis-persistence/target/classes/"
#oxalis.persister.receipt = "file:///software/git/oxalis/oxalis-persistence/target/classes/" 

# logfile
oxalis.logging.config = logback-oxalis.xml
```

Br,
Kenneth

**Comment by zonenet** [comment]
Hi Kenneth, did you ever find a solution for this?
@keriks99

**Comment by keriks99** [comment]
@zonenet no, I did not get the database storage to work so far. However, @klakegg confirmed verbally that the statistics-function has been removed from Oxalis, although the documentation does not say so.

**Comment by RvanMaarenApro** [comment]
Same problem over here, using oxalis 4.0.4. Is statistics still a relevant option or is it deprecated ?

**Comment by SuperJuell** [comment]
This issue is closed due to age, old versions and lack of activity.
