### ISSUE TITLE
Oxalis support MySQL database

### ISSUE THREAD

**Issue by itEnercomSwiss** [OxalisCommunity/oxalis#336]
Hi everybody.

I chose to use Oxalis for total compatibility with PEPPOL. I need to record the input and output streams in a MySQL database. How can I configure Oxalis with a MySQL database? Where can I get the pre script to build the database tables for Oxalis? I did not understand where to take this reference.

Thanks in advance

Best regards
Davide

**Comment by itEnercomSwiss** [comment]
Hi,
I reopen this ticket. 
Does Oxalis 4.0.2 support MySQL? In the configuration guide I can not detect this.

Best regards
Davide

**Comment by SuperJuell** [comment]
This issue is closed due to age, old versions and lack of activity.
