### ISSUE TITLE
Unable to start custom module with tomcat

### ISSUE THREAD

**Issue by klopojed** [OxalisCommunity/oxalis#338]
Hello,

I'm trying to do the following: run oxalis-inbound.war in tomcat with my own module being loaded from tomcat lib/custom-inbound.jar

During the load it fails with ClassCastException stating that CustomModule is not an instance of Module (of course it is).

I dug into it and found out that custom-inbound.jar is being loaded by tomcat with another class loader than oxalis-inbound.war and each class loader has own copy of Module.class. In that case it is not possible to cast a class to "another" Module even when the class hierarchy is correct

**Comment by kdkanishka** [comment]
I also have the same problem!  This issue preventing me updating to latest oxalis since my custom module face this same issue.

**Comment by klopojed** [comment]
More information. I put some logging into GuiceModuleLoader.loadModule, and here are the results for one of the Oxalis classes and my CustomModule in the following order:

- input class name
- created object, to be sure it is created
- test instanceof(Module)
- class hierarchy with interfaces
- check that received Module interface equals to the previous one
- ClassLoader.toString()

---

13:29:53.604 [main] DEBUG no.difi.oxalis.commons.guice.GuiceModuleLoader - Loading module 'no.difi.oxalis.commons.filesystem.FileSystemModule'.
Classname: no.difi.oxalis.commons.filesystem.FileSystemModule
Test object: no.difi.oxalis.commons.filesystem.FileSystemModule@69b66787
Is instance of Module: true
 -> no.difi.oxalis.commons.filesystem.FileSystemModule
 -> no.difi.oxalis.commons.guice.OxalisModule
 -> com.google.inject.AbstractModule
        interface com.google.inject.Module
     equals previous: true
        ParallelWebappClassLoader
  context: oxalis-inbound-4.0.1
  delegate: false
-> Parent Classloader:
java.net.URLClassLoader@31cefde0
`
13:29:53.604 [main] DEBUG no.difi.oxalis.commons.guice.GuiceModuleLoader - Loading module 'x.x.x.CustomModule'.
Classname: x.x.x.CustomModule
Test object: x.x.x.CustomModule@47d6a31a
Is instance of module: false <-- **here is the failure point**
 -> com.opuscapita.peppol.inbound.InboundModule
 -> no.difi.oxalis.commons.guice.OxalisModule
 -> com.google.inject.AbstractModule
        interface com.google.inject.Module <-- **seems to be correct?**
     equals previous: false <-- **but not equals to the Module interface of FileSystemModule**!
        java.net.URLClassLoader@31cefde0 <-- **here it goes - other class loader**
 -> java.lang.Object

java.lang.ClassCastException: com.opuscapita.peppol.inbound.InboundModule cannot be cast to com.google.inject.Module`

**Comment by darklajid** [comment]
I'm not a Java guy per se (and this is potentially outdated as an issue?), but it seems to me that you have two versions of com.google.inject.Module on your class path.

You didn't share a lot about your custom module, but maybe it pulls in and bundles its very own (potentially conflicting) library?

**Comment by SuperJuell** [comment]
This issue is closed due to age and lack of activity.
