### ISSUE TITLE
How to set up the statistics in oxalis v4.0.2

### ISSUE THREAD

**Issue by christian-andersson** [OxalisCommunity/oxalis#347]
Difi requires us to gather statistics on the usage of the different documents types.
With 3.2 it was automaticly gathered into the raw_stats table in mysql for us.

but with 4.0.2 war, this does not come out of the box automatically.

What is needed to be done for this to work again?
(The documentation is severely lacking in this department)

**Comment by christian-andersson** [comment]
I have added the database connection configuration
oxalis.database.datasource = dbcp
oxalis.database.driver.path = "/opt/oxalis-home/mysql-connector-java-5.1.46.jar"
oxalis.database.driver.class = "com.mysql.jdbc.Driver"
oxalis.database.jdbc.connection = "jdbc:mysql://db:3306/oxalis"
oxalis.database.jdbc.username = oxalis
oxalis.database.jdbc.password = oxalis

but oxalis 4.0.2 does not seem to even try to connect to the database

also after much searching I added the 

oxalis.statistics.service = no.difi.oxalis.statistics.service.DefaultStatisticsService

settings since this setting is apperently set to the NoopStatisticsService, but still no conenctiosn to the database and no data in the database.

**Comment by zeko78** [comment]
Works against Azure SQL db using the following config:

```
oxalis.statistics.service=default
oxalis.database.driver.class=com.microsoft.sqlserver.jdbc.SQLServerDriver
oxalis.database.driver.path="/home/xxx/sqljdbc_6.0/enu/jre8/sqljdbc42.jar"
oxalis.database.jdbc.connection="jdbc:sqlserver://xxx.database.windows.net:1433;databaseName=yyy;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net"
oxalis.database.jdbc.username="zzz@aaa"
oxalis.database.jdbc.password="bbb"
```

**Comment by SuperJuell** [comment]
This issue is closed due to age, old versions and lack of activity.
