### ISSUE TITLE
Warning message in Tomcat' standard error log

### ISSUE THREAD

**Issue by monze** [OxalisCommunity/oxalis#372]
Hello

We are now using Oxalis version 4.0.3-Snapshot (revision 1412).
We have wrapped the outbound module in a shallow .war project (so our C# code can communicate with java though REST) and deployed both outbound and inbound on a Tomcat server. This is a setup that has work without problem in many years.
After updating to Oxalis 4.x, we now see this error message in the tomcat8.5-stderr log-file:

`
18-Oct-2018 15:05:50.470 WARNING [http-nio-80-exec-17] com.google.inject.internal.ProxyFactory.<init> Method [public java.lang.Object no.difi.oxalis.persistence.platform.PlatformProvider.get()] is synthetic and is being intercepted by [no.difi.oxalis.persistence.aop.RepositoryConnectionMethodInterceptor@eb7828]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
`

Is it a bug in Oxalis, or have we configure Oxalis wrong (and what are we doing wrong...) ?

The statistic module works like expected as the table in mySql is filled.

Jacob Mogensen
mySupply ApS
Denmark

**Comment by SuperJuell** [comment]
This issue is closed due to age, old versions and lack of activity.
