### ISSUE TITLE
[AS2] S/MIME canonicalization of application/xml with <CR><LF>

### ISSUE THREAD

**Issue by descala** [OxalisCommunity/oxalis#382]
As per RFC 3851 https://tools.ietf.org/html/rfc3851#section-3.1.1

>    entities of major type "text" MUST have both their line endings and
>    character set canonicalized.  The line ending MUST be the pair of
>    characters <CR><LF>

if I use Oxalis to send a payload with only LF, the S/MIME digest is calculated without canonicalization. when I use OpenSSL to verify the signature it is always invalid, because OpenSSL canonicalizes before digesting.

when I use OpenSSL to calculate the AS2 MIC, it always differs for the same reason.

if I send a payload with CR LF "Windows style" it all works as expected, because the file is S/MIME-canonical beforehand.

is it a PEPPOL specific parametrization of AS2? is not application/xml considered of "major type text"?

**Comment by aaron-kumar** [comment]
Closing this issue since as per OpenPeppol, AS2 is Optional protocol starting 2020-02-01 and AS2 protocol will be removed soon.
We in Oxalis community also starting process to deprecate and removing AS2 protocol support completely from Oxalis.
