### ISSUE TITLE
Oxalis server does not shutdown properly

### ISSUE THREAD

**Issue by jonassss** [OxalisCommunity/oxalis#388]
On commit cde96ba

The application is still running after it exits normally.
Seeing behaviour on both oxalis (server) and oxalis standalone (runnable jar).
For oxalis, this is after calling tomcat bin/shutdown.sh, for standalone this is after running the jar.

How to reproduce:
ps -ef | grep java (To take a look at your processes)
<your path>/tomcat9/bin/startup.sh 
** wait for startup **
ps -ef | grep java (Note down the new process id)
<your path>/tomcat9/bin/shutown.sh
** wait for shutdown ** 
ps -ef | grep java (You will now see the process still running)

**Comment by RvanMaarenApro** [comment]
Tried to reproduce it on 5.1.0 with AS4 unfortunately not able to reproduce. Any specific situations/circumstances here ?

Regards,

Richard

**Comment by aaron-kumar** [comment]
Unable to reproduce ... No response, how to reproduce since more than 1 year... Closing issue...
If you will face issue again then please write how to reproduce issue... and open issue.
