### ISSUE TITLE
Where is InstanceIdentifier of my SBDH is receipt file ?

### ISSUE THREAD

**Issue by cook32** [OxalisCommunity/oxalis#397]
I am using my Pilot oxalis AP to send some tests files with already built SBDH.

I have a success delivery with a nice receipt file but I am unable to find my original InstanceIdentifier uuid set in my SBDH under <DocumentIdentification> tag.

Please could you help me ?

Of course it is required to be able to match original sent file and monitor delivery.

Thanks a lot

VR

**Comment by SuperJuell** [comment]
This issue is closed due to age and lack of activity.
