### ISSUE TITLE
why is the one test inAs2InboundHandlerTest actually disabled in 4.0.4/4.1.0/master

### ISSUE THREAD

**Issue by open-gdsn** [OxalisCommunity/oxalis#446]
Currently here is actually/effectively no test of this class since the one test that is there is disabled

https://github.com/difi/oxalis/blob/5607d9ff79ea2f3bb8763e72b7eef9bd7cae1903/oxalis-extension/oxalis-as2/src/test/java/no/difi/oxalis/as2/inbound/As2InboundHandlerTest.java#L111

    @Test(enabled = false)
    public void testReceive() throws Exception {
        ...
    }

 I know all pieces that are used in it are individually tests and have no errors, but as a 'integration' class, the `As2InboundHandler` is rather important and now has no tests.

And when I enable it, an error is thrown about the message not being a singed one. This can traced to the structure of the test where the generated headers of the signed message (content type, boudnary, mic) are not added to the headers that are used to process the message.

**Comment by aaron-kumar** [comment]
Closing this issue since as per OpenPeppol, AS2 is Optional protocol starting 2020-02-01 and AS2 protocol will be removed soon.
We in Oxalis community also starting process to deprecate and removing AS2 protocol support completely from Oxalis.
