### ISSUE TITLE
Question on inbound logging

### ISSUE THREAD

**Issue by RvanMaarenApro** [OxalisCommunity/oxalis#450]
Hi,

In general a question but not an issue, what should be the general approach on having additional incoming logging ? Enable debug on logback.xml ?

Any information is appreciated.

Regards,

Richard

**Comment by darklajid** [comment]
What do you want to log and why? Without the motivation it's kinda hard to answer the question.
For example, maybe you _actually_ want to write statistics and the statistics extension points might be what interests you? But without more information this seems rather broad and open-endeded.

**Comment by RvanMaarenApro** [comment]
Hi, Thank you for your feedback, Basically I would like to keep track of what is incoming, what is received from where etc. I am quite new on Oxalis, could you give me some more background on the statistics extentions ? Based  on the documentation this should reside at /oxalis/statistics but this seems not implemented on my side.

Regards,

Richard
