### ISSUE TITLE
AS4 Inbound - lot of .dat files in server

### ISSUE THREAD

**Issue by kdkmadusanka** [OxalisCommunity/oxalis#464]
HI,

Recently we have update the AS4 version to 4.1.3 and after that i can see lot of .dat files are saving out of the IN folder.
My inbound folder set up to '/home/ubuntu/IN/' and I can see .dat files in '/home/ubuntu/'.

**Comment by FrodeBjerkholt** [comment]
The storage location has nothing to do with the AS4 plugin, so I move the question to the main oxalis repostory,

**Comment by SuperJuell** [comment]
The file is a receipt, need to be configured locally.
