### ISSUE TITLE
Suggestion for documentation: configure correct trusted certificate list on sending access points

### ISSUE THREAD

**Issue by tjeb** [OxalisCommunity/oxalis#477]
Hi,

after solving some operational issues for some of our members, I would like to suggest an addition to the installation guide: have people verify that they use the correct trusted TLS certificate list, as the one bundled with Java is not the one required by the PEPPOL Policy for Transport Security.

I wrote a rather longish article explaining the issue: https://ionite.net/newsblog/2020-06-29_peppol_tls_certificates/

(Please note, I am not asking to link to it in the documentation, but to simply add a bullet point so that people set up the correct TLS trust store on their sending access points)

**Comment by aaron-kumar** [comment]
Documentation link added as part of commit : aa359fed2c9842502b478dae32a463facb9d4cdc
