### ISSUE TITLE
Oxalis server/Inbound and Tomcat same url (change in server/inbound)

### ISSUE THREAD

**Issue by LasseAtomic** [OxalisCommunity/oxalis#483]
Hi guys

I'm new to peppol but have managed to get oxalis in and outbound working.
For now I might have to switch between tomcat and server/inbound receiving, but tomcat binds to http://localhost/oxalis/as4 whereas server/inbound binds to http://localhost/as4.
Can I change the server/inbound binding to also be http://localhost/oxalis/as4 ? I cannot see any config for that jetty server

best 
Lasse

**Comment by SuperJuell** [comment]
This is a local configuration issue.
