### ISSUE TITLE
activate oxalis-api

### ISSUE THREAD

**Issue by LasseAtomic** [OxalisCommunity/oxalis#484]
Hi guys

I'm new to peppol but have managed to get oxalis in- (tomcat) and outbound (standalone) working.

How can I activate the oxalis-api?
I have found the jar file, but how to enable it??

best 
Lasse

**Comment by artjomsk** [comment]
It's not API you're waiting for - not REST API with ability to send/get documents. It's module used by Oxalis internally.

**Comment by artjomsk** [comment]
There are some extension points when you can override or add some functionality to Oxalis. So, readme says that Oxalis can be used as standalone app or can be extended with your code. API word maybe is misleading.

P.S. All my answers may not be 100% correct. I'm not related to Difi or Peppol. I'm not contributor of the project, too. Just active user.

**Comment by LasseAtomic** [comment]
Thank you for the reply!
It is highly appreciated.

I’m trying to get a hold on it 😊



Med venlig hilsen

Lasse Schulin-Zeuthen
Atomic Software aps
Support 88 88 78 40 / support@atomic.dk<mailto:support@atomic.dk>
Direkte: 88 88 78 48 / lasse@atomic.dk<mailto:lasse@atomic.dk>


Fra: artjomsk <notifications@github.com>
Sendt: 24. august 2020 08:30
Til: difi/oxalis <oxalis@noreply.github.com>
Cc: Lasse Schulin-Zeuthen <lasse@atomic.dk>; Author <author@noreply.github.com>
Emne: Re: [difi/oxalis] activate oxalis-api (#484)


There are some extension points when you can override or add some functionality to Oxalis. So, readme says that Oxalis can be used as standalone app or can be extended with your code. API word maybe is misleading.

P.S. All my answers may not be 100% correct. I'm not related to Difi or Peppol. I'm not contributor of the project, too. Just active user.
