### ISSUE TITLE
Folderstructure of inbound files

### ISSUE THREAD

**Issue by LasseAtomic** [OxalisCommunity/oxalis#485]
I have just setup a tomcat inbound.
FIles are placed in /recipient-id/sender-id/file.dat + file.xml
Can I control that so just all xml files in /inbound/ or something like that.
That is much easier to parse afterward..
Even though I still has to unwrap form sbdh headers...

**Comment by arnemorten** [comment]
I guess you write your own Persisterhandler. From the Readme:

`Out of the box it persists inbound messages to the filesystem. Persistence have been modularized so you can provide your own implementation if you need to send inbound messages to a message queue, a workflow engine, a document archive or others.`

**Comment by LasseAtomic** [comment]
Thank you for your reply
I hadsee.. 
I was mostly wondering of there were a config-tag all ready doing it, if so I would like to enable it.. :)
