### ISSUE TITLE
Multiple Oxalis Inbound Instances (TEST and PROD)

### ISSUE THREAD

**Issue by simo385** [OxalisCommunity/oxalis#490]
Hello,

we'd like use the same Tomcat web server to run TEST and PROD Oxalis Instances.

is it possible to run two Oxalis Instance (different configuration and different certificates) into the same Tomcat web server?

Thanks in advance,
Simone

**Comment by aksamit** [comment]
Hi Simone,

I believe it should be achievable if you separate the two different configurations. I have never tried it myself though. 

However, Oxalis is using WSS4J and the following issue might be a problem you will hit: https://issues.apache.org/jira/browse/WSS-660

BR, Mikael Aksamit

**Comment by simo385** [comment]
Hi @aksamit,

the above link relating to the Applications running on the same Tomcat. Would be possible to use two different Tomcat on the same virtual machine?

Thanks in advance,
Simone

**Comment by tjeb** [comment]
I have tried running both instances from the same tomcat server and did indeed run into classloading issues; they worked for a while initially, but at some point one would start failing.

Running two separate instances of tomcat is indeed possible on a single machine, and that was my solution. It requires a bit more manual setup (mainly to run them on different ports, and using different URLs for the endpoints), but it works like a charm.
