### ISSUE TITLE
Question on smk lookup

### ISSUE THREAD

**Issue by RvanMaarenApro** [OxalisCommunity/oxalis#499]
Hi,

Very strange situation, testing with galaxy lookup on test environments worked fine. At some point in time it started to fail when looking up the participant. Error message is: Unable to fetch 'http://testsmp.galaxygateway.euhttp/

For some reason it is adding an additional http at the end.

Question, how does it know which smk it should use ? Anyone seen this before ?

Best regards,

Richard

ful message : 

Log from oxalis:2021-02-09 12:05:25,337  DEBUG [org.apache.http.impl.execchain.MainClientExec] Connection discarded
Log from oxalis:2021-02-09 12:05:25,337  DEBUG [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection released: [id: 2][route: {}->http://testsmp.galaxygateway.euhttp:80][total kept alive: 1; route allocated: 0 of 2; total allocated: 1 of 20]
Log from oxalis:
Log from oxalis:Message failed : Unable to fetch 'http://testsmp.galaxygateway.euhttp/iso6523-actorid-upis%3A%3A0106%3A999912344/services/busdox-do......

**Comment by RvanMaarenApro** [comment]
Appologies, this was found already it seems and fixed by lookup.locator.class=no.difi.vefa.peppol.lookup.locator.BusdoxLocator

**Comment by aaron-kumar** [comment]
Thanks a lot for identifying that solution to this already documented in README file and also mentioned in issue# https://github.com/OxalisCommunity/oxalis/issues/498

We recommend that please browse closed and open issue before creating new one. Thanks for cooperation !!!
