### ISSUE TITLE
Sending of invoice to denmark. Combination of receiver and document type identifier.

### ISSUE THREAD

**Issue by runholen** [OxalisCommunity/oxalis#512]
Hi. EHF has been working fine for Norwegian customers, but we would like to try to extend to sending EHF to a danish customer.
The EHF validates ok, but when trying to send it, the oxalis server gives the following message:
ERROR: no.difi.oxalis.api.lang.OxalisTransmissionException: Combination of receiver (iso6523-actorid-upis::0198:40464387) and document type identifier (busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0::2.1) is not supported.
What do I have to change to be able to send EHFs to a danish receiver?

**Comment by jannewaren** [comment]
To me it looks like the participant `0198:40464387` is not registered to receive any document types in the Peppol network. The participant seems to be registered in SMP, but the SMP returns an empty <ServiceMetadataReferenceCollection> element which means no documents can be sent.

You can see the SMP reply yourself by going to http://b-7ab7d9d291d2cd7fbc85ce9db9c52dd4.iso6523-actorid-upis.edelivery.tech.ec.europa.eu/iso6523-actorid-upis::0198:40464387 with a normal web browser.

Something needs to be done to this participant in the SMP in question (seems to be Tickstar). As far as I can see this is not related to Oxalis.

**Comment by runholen** [comment]
Thank you very much for your reply. We will check this with the Danish customer.
