### ISSUE TITLE
How to integtrate full Peppol message validation

### ISSUE THREAD

**Issue by kukel** [OxalisCommunity/oxalis#539]
I have been looking into full Peppol message validation before sending out messages or when receiving. I (think I) want this to be integrated into Oxalis and not as a standalone post- or pre- service. I am unable to find the right place in the code for this. Is there a good way/hook to do this or should I take a different approach?

Part of this is related to https://docs.peppol.eu/poacc/upgrade-3/profiles/36-mlr/

Any thoughts?

**Comment by aaron-kumar** [comment]
Oxalis is [Access Point software implementation](https://peppol.eu/downloads/peppolimplementations/) (AS2 and AS4) based on [Access Point Specification](https://peppol.eu/downloads/the-peppol-edelivery-network-specifications/)
Adding message validation support for global/country specific rules is outside the scope of Oxalis. You can easily integrate Open source validation library/solution with your product/application. 

P.S. I am converting this issue to discussion as it is not bug.
