### ISSUE TITLE
Java 8 EOL

### ISSUE THREAD

**Issue by Footur** [OxalisCommunity/oxalis#542]
Java 8 is required for the use of Oxalis. Support for Java 8 expires in March 2022. Will Java 11 or Java 17 be supported until then?

[Oracle Java SE Support Roadmap](https://www.oracle.com/java/technologies/java-se-support-roadmap.html)

**Comment by aaron-kumar** [comment]
@Footur Thanks for being alert, raising your concern/voice. 
Yes, we are already working on Java upgrade for Oxalis and associated dependencies. We are targeting Java 16 and above. More information including transition plan (java 8 to Java 16) will shared via Oxalis Community email channel. Stay tuned !!!

**Comment by Footur** [comment]
Thank you @aaron-kumar for the answer. Would be nice to see support for Java 17 (it has LTS).

**Comment by dladlk** [comment]
Moreover, Java 17 from Oracle got a new license - again free for commercial usage - https://www.oracle.com/downloads/licenses/no-fee-license.html

Makes new java versions attractive again...

**Comment by aaron-kumar** [comment]
Closing this as "issue" since it is now an item in Oxalis Roadmap
