### ISSUE TITLE
As2Servlet clears the MDC

### ISSUE THREAD

**Issue by renaudcodabox** [OxalisCommunity/oxalis#577]
Hello, 

We have run into an issue where the MDC was unexpectedly cleared.
After some investigation we found that the `As2Servlet` is clearing the MDC at the end of the `doPost` method.
Is it possible to only remove the values from the MDC that oxalis has added?

**Comment by aaron-kumar** [comment]
Fixed in 2181ffb0c65b83b46854738956fca604d1b12558
