### ISSUE TITLE
sending invoice to other Access Point issue

### ISSUE THREAD

**Issue by tranthanhtam8890** [OxalisCommunity/oxalis#593]
Hi Oxalis team,

I am Tam from Oryton AS. We are using Oxalis to send and receive EHF. The services work well for receive EHF, send EHF in local AP.
But we got issue when send EHF to other AP through we get success status at all,

Here is detail log of Oxalis

0|EHF service  | 2022-06-07 11:22:08,706 INFO [network.oxalis.commons.filesystem.detector.EnvironmentHomeDetector] Using Oxalis folder specified as environment variable 'OXALIS_HOME' with value '/opt/tomcat9/.oxalis'.
0|EHF service  | 2022-06-07 11:22:08,719 INFO [network.oxalis.commons.filesystem.FileSystemModule] Home folder: /opt/tomcat9/.oxalis
0|EHF service  | 2022-06-07 11:22:08,720 INFO [network.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /opt/tomcat9/.oxalis
0|EHF service  | 2022-06-07 11:22:08,720 INFO [network.oxalis.commons.config.ConfigModule] Configuration file: /opt/tomcat9/.oxalis/oxalis.conf
0|EHF service  | 2022-06-07 11:22:08,729 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => CONF:
0|EHF service  | 2022-06-07 11:22:08,730 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: /var/peppol/IN
0|EHF service  | 2022-06-07 11:22:08,730 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: <null>
0|EHF service  | 2022-06-07 11:22:10,257 INFO [network.oxalis.commons.filesystem.detector.EnvironmentHomeDetector] Using Oxalis folder specified as environment variable 'OXALIS_HOME' with value '/opt/tomcat9/.oxalis'.
0|EHF service  | 2022-06-07 11:22:10,257 INFO [network.oxalis.commons.filesystem.FileSystemModule] Home folder: /opt/tomcat9/.oxalis
0|EHF service  | 2022-06-07 11:22:10,257 INFO [network.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /opt/tomcat9/.oxalis
0|EHF service  | 2022-06-07 11:22:10,258 INFO [network.oxalis.commons.config.ConfigModule] Configuration file: /opt/tomcat9/.oxalis/oxalis.conf
0|EHF service  | 2022-06-07 11:22:10,259 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_TOTAL: 20
0|EHF service  | 2022-06-07 11:22:10,259 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_MAX_ROUTE: 2
0|EHF service  | 2022-06-07 11:22:10,259 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_VALIDATE_AFTER_INACTIVITY: 1000
0|EHF service  | 2022-06-07 11:22:10,260 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_TIME_TO_LIVE: 30
0|EHF service  | 2022-06-07 11:22:10,260 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_CONNECT: 0
0|EHF service  | 2022-06-07 11:22:10,260 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_READ: 0
0|EHF service  | 2022-06-07 11:22:10,260 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_SOCKET: 0
0|EHF service  | 2022-06-07 11:22:10,260 INFO [network.oxalis.commons.settings.SettingsBuilder] Error => TRACKER: quiet
0|EHF service  | 2022-06-07 11:22:10,260 INFO [network.oxalis.commons.settings.SettingsBuilder] AS2 => NOTIFICATION: not.in.use@difi.no
0|EHF service  | 2022-06-07 11:22:10,260 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => CONF:
0|EHF service  | 2022-06-07 11:22:10,260 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: /var/peppol/IN
0|EHF service  | 2022-06-07 11:22:10,260 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: <null>
0|EHF service  | 2022-06-07 11:22:10,260 INFO [network.oxalis.commons.settings.SettingsBuilder] Identifiers => HOSTNAME:
0|EHF service  | 2022-06-07 11:22:10,260 INFO [network.oxalis.commons.settings.SettingsBuilder] Identifiers => MSGID_GENERATOR: default
0|EHF service  | 2022-06-07 11:22:10,261 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => PATH: /opt/tomcat9/.oxalis/2021/oxalis-keystore-2021.jks
0|EHF service  | 2022-06-07 11:22:10,261 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => PASSWORD: ************
0|EHF service  | 2022-06-07 11:22:10,261 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => KEY_ALIAS: 1
0|EHF service  | 2022-06-07 11:22:10,261 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => KEY_PASSWORD: ************
0|EHF service  | 2022-06-07 11:22:10,261 INFO [network.oxalis.commons.settings.SettingsBuilder] Header => PARSER: sbdh
0|EHF service  | 2022-06-07 11:22:10,261 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => PAYLOAD: default
0|EHF service  | 2022-06-07 11:22:10,262 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => RECEIPT: default
0|EHF service  | 2022-06-07 11:22:10,262 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => EXCEPTION: default
0|EHF service  | 2022-06-07 11:22:10,262 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => HANDLER: default
0|EHF service  | 2022-06-07 11:22:10,262 INFO [network.oxalis.commons.settings.SettingsBuilder] Tracing => REPORTER: noop
0|EHF service  | 2022-06-07 11:22:10,263 INFO [network.oxalis.commons.settings.SettingsBuilder] Tracing => HTTP: <null>
0|EHF service  | 2022-06-07 11:22:10,263 INFO [network.oxalis.commons.settings.SettingsBuilder] Tracing => TRACER: noop
0|EHF service  | 2022-06-07 11:22:10,263 INFO [network.oxalis.commons.settings.SettingsBuilder] Executor => DEFAULT: 50
0|EHF service  | 2022-06-07 11:22:10,263 INFO [network.oxalis.commons.settings.SettingsBuilder] Executor => STATISTICS: 50
0|EHF service  | 2022-06-07 11:22:10,263 INFO [network.oxalis.commons.settings.SettingsBuilder] Tag => GENERATOR: noop
0|EHF service  | 2022-06-07 11:22:10,263 INFO [network.oxalis.commons.settings.SettingsBuilder] Timestamp => SERVICE: system
0|EHF service  | 2022-06-07 11:22:10,263 INFO [network.oxalis.commons.settings.SettingsBuilder] Evidence => SERVICE: rem
0|EHF service  | 2022-06-07 11:22:10,263 INFO [network.oxalis.commons.settings.SettingsBuilder] Transformer => DETECTOR: noop
0|EHF service  | 2022-06-07 11:22:10,264 INFO [network.oxalis.commons.settings.SettingsBuilder] Transformer => WRAPPER: xml
0|EHF service  | 2022-06-07 11:22:10,264 INFO [network.oxalis.commons.settings.SettingsBuilder] Statistics => SERVICE: noop
0|EHF service  | 2022-06-07 11:22:10,264 INFO [network.oxalis.commons.settings.SettingsBuilder] Transmission => VERIFIER: default
0|EHF service  | 2022-06-07 11:22:10,264 INFO [network.oxalis.commons.settings.SettingsBuilder] AS4 => HOSTNAME:
0|EHF service  | 2022-06-07 11:22:10,264 INFO [network.oxalis.commons.settings.SettingsBuilder] AS4 => MSGID_GENERATOR: default
0|EHF service  | 2022-06-07 11:22:10,264 INFO [network.oxalis.commons.settings.SettingsBuilder] AS4 => TYPE: peppol
0|EHF service  | 2022-06-07 11:22:10,264 INFO [network.oxalis.commons.settings.SettingsBuilder] Logging => CONFIG: <null>
0|EHF service  | 2022-06-07 11:22:10,264 INFO [network.oxalis.commons.settings.SettingsBuilder] Logging => SERVICE: logback
0|EHF service  | 2022-06-07 11:22:10,351 INFO [network.oxalis.commons.security.CertificateModule] Certificate subject: CN=PNO000318, OU=PEPPOL PRODUCTION AP, O=Oryton AS, C=NO
0|EHF service  | 2022-06-07 11:22:10,351 INFO [network.oxalis.commons.security.CertificateModule] Certificate issuer: CN=PEPPOL ACCESS POINT CA - G2, O=OpenPEPPOL AISBL, C=BE
0|EHF service  | 2022-06-07 11:22:10,522 INFO [network.oxalis.vefa.peppol.security.ModeDetector] Detection error (TEST): Validation of subject principal(CN) failed.
0|EHF service  | 2022-06-07 11:22:10,525 INFO [network.oxalis.vefa.peppol.security.ModeDetector] Detection error (LOCAL): Certificate should be self-signed.
0|EHF service  | 2022-06-07 11:22:11,206 INFO [network.oxalis.vefa.peppol.security.ModeDetector] Detected mode: PRODUCTION
0|EHF service  | 2022-06-07 11:22:11,212 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] Prioritized list of transport profiles:
0|EHF service  | 2022-06-07 11:22:11,212 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => peppol-transport-as4-v2_0
0|EHF service  | 2022-06-07 11:22:11,212 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => bdxr-transport-ebms3-as4-v1p0
0|EHF service  | 2022-06-07 11:22:11,213 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1
0|EHF service  | 2022-06-07 11:22:11,213 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver2p0
0|EHF service  | 2022-06-07 11:22:11,213 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0
0|EHF service  | 2022-06-07 11:22:11,563 WARN [network.oxalis.outbound.transmission.TransmissionRequestBuilder] Endpoint was set by caller not retrieved from SMP, make sure this is intended behaviour.
0|EHF service  | 2022-06-07 11:22:12,194 WARN [org.apache.cxf.ws.policy.AssertionBuilderRegistryImpl] No assertion builder for type {http://oxalis.network/custom/security-policy}Basic128GCMSha256MgfSha256 registered.
0|EHF service  | 91d33468-4501-47f8-b508-72f1ac6012e9@EHFAndBankSftponly transmission took 3943 ms
0|EHF service  | Average transmission time was 3943.0ms
0|EHF service  | Total time spent: 4s
0|EHF service  | Attempted to send 1 files
0|EHF service  | Failed transmissions: 0
0|EHF service  | Transmission speed 0 documents per second
[catalina.log](https://github.com/OxalisCommunity/oxalis/files/8852002/catalina.log)

I had tried many solutions but can't resolve it. Hope get help from Oxalis team.
Thank and regard!

**Comment by RvanMaarenApro** [comment]
Hi,

Strange, it seems your payload is persisted in the logging of tomcat if I understand you correctly ?

Regards,

Richard

**Comment by aaron-kumar** [comment]
WARN (warning) - "_Endpoint was set by caller not retrieved from SMP, make sure this is intended behaviour._" clearly indicate what exactly wrong thing you are doing. 

> https://github.com/OxalisCommunity/oxalis/blob/fe32fff8589c47e9922d8673f4fb4f7770b8beb2/oxalis-outbound/src/main/java/network/oxalis/outbound/transmission/TransmissionRequestBuilder.java

        // If the endpoint has not been overridden by the caller, look up the endpoint address in
        // the SMP using the data supplied in the payload
        if (isEndpointSuppliedByCaller() && isOverrideAllowed()) {
            log.warn("Endpoint was set by caller not retrieved from SMP, make sure this is intended behaviour.");
        } else {
            Endpoint endpoint = lookupService.lookup(effectiveStandardBusinessHeader.toVefa(), null);

            if (isEndpointSuppliedByCaller() && !this.endpoint.equals(endpoint)) {
                throw new IllegalStateException("You are not allowed to override the EndpointAddress from SMP.");
            }

            this.endpoint = endpoint;
        }

Because of above overidding setting by you, library is not doing proper SML/SMP lookup but _overriding_ its behavior to send document to your local simulated destination AP which may be configured by you for your local testing. Do Not override this behavior in production system where you want to send documents to remote AP.

**Comment by tranthanhtam8890** [comment]
@aaron-kumar Thank for your reply!

I just updated code and the log don't show that warning anymore.
But seem issue still not resolve. Just local AP participant can receive EHF and the others AP receive nothing.

New log:
0|EHF service  | 2022-06-08 03:30:30,800 INFO [network.oxalis.commons.filesystem.detector.EnvironmentHomeDetector] Using Oxalis folder specified as environment variable 'OXALIS_HOME' with value '/opt/tomcat9/.oxalis'.
0|EHF service  | 2022-06-08 03:30:30,808 INFO [network.oxalis.commons.filesystem.FileSystemModule] Home folder: /opt/tomcat9/.oxalis
0|EHF service  | 2022-06-08 03:30:30,809 INFO [network.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /opt/tomcat9/.oxalis
0|EHF service  | 2022-06-08 03:30:30,809 INFO [network.oxalis.commons.config.ConfigModule] Configuration file: /opt/tomcat9/.oxalis/oxalis.conf
0|EHF service  | 2022-06-08 03:30:30,816 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => CONF:
0|EHF service  | 2022-06-08 03:30:30,817 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: /var/peppol/IN
0|EHF service  | 2022-06-08 03:30:30,817 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: <null>
0|EHF service  | 2022-06-08 03:30:32,162 INFO [network.oxalis.commons.filesystem.detector.EnvironmentHomeDetector] Using Oxalis folder specified as environment variable 'OXALIS_HOME' with value '/opt/tomcat9/.oxalis'.
0|EHF service  | 2022-06-08 03:30:32,162 INFO [network.oxalis.commons.filesystem.FileSystemModule] Home folder: /opt/tomcat9/.oxalis
0|EHF service  | 2022-06-08 03:30:32,162 INFO [network.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /opt/tomcat9/.oxalis
0|EHF service  | 2022-06-08 03:30:32,162 INFO [network.oxalis.commons.config.ConfigModule] Configuration file: /opt/tomcat9/.oxalis/oxalis.conf
0|EHF service  | 2022-06-08 03:30:32,164 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_TOTAL: 20
0|EHF service  | 2022-06-08 03:30:32,165 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_MAX_ROUTE: 2
0|EHF service  | 2022-06-08 03:30:32,165 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_VALIDATE_AFTER_INACTIVITY: 1000
0|EHF service  | 2022-06-08 03:30:32,165 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_TIME_TO_LIVE: 30
0|EHF service  | 2022-06-08 03:30:32,165 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_CONNECT: 0
0|EHF service  | 2022-06-08 03:30:32,165 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_READ: 0
0|EHF service  | 2022-06-08 03:30:32,165 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_SOCKET: 0
0|EHF service  | 2022-06-08 03:30:32,165 INFO [network.oxalis.commons.settings.SettingsBuilder] Error => TRACKER: quiet
0|EHF service  | 2022-06-08 03:30:32,165 INFO [network.oxalis.commons.settings.SettingsBuilder] AS2 => NOTIFICATION: not.in.use@difi.no
0|EHF service  | 2022-06-08 03:30:32,165 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => CONF:
0|EHF service  | 2022-06-08 03:30:32,165 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: /var/peppol/IN
0|EHF service  | 2022-06-08 03:30:32,166 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: <null>
0|EHF service  | 2022-06-08 03:30:32,166 INFO [network.oxalis.commons.settings.SettingsBuilder] Identifiers => HOSTNAME:
0|EHF service  | 2022-06-08 03:30:32,166 INFO [network.oxalis.commons.settings.SettingsBuilder] Identifiers => MSGID_GENERATOR: default
0|EHF service  | 2022-06-08 03:30:32,166 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => PATH: /opt/tomcat9/.oxalis/2021/oxalis-keystore-2021.jks
0|EHF service  | 2022-06-08 03:30:32,166 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => PASSWORD: ************
0|EHF service  | 2022-06-08 03:30:32,166 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => KEY_ALIAS: 1
0|EHF service  | 2022-06-08 03:30:32,166 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => KEY_PASSWORD: ************
0|EHF service  | 2022-06-08 03:30:32,167 INFO [network.oxalis.commons.settings.SettingsBuilder] Header => PARSER: sbdh
0|EHF service  | 2022-06-08 03:30:32,167 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => PAYLOAD: default
0|EHF service  | 2022-06-08 03:30:32,167 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => RECEIPT: default
0|EHF service  | 2022-06-08 03:30:32,167 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => EXCEPTION: default
0|EHF service  | 2022-06-08 03:30:32,167 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => HANDLER: default
0|EHF service  | 2022-06-08 03:30:32,167 INFO [network.oxalis.commons.settings.SettingsBuilder] Tracing => REPORTER: noop
0|EHF service  | 2022-06-08 03:30:32,167 INFO [network.oxalis.commons.settings.SettingsBuilder] Tracing => HTTP: <null>
0|EHF service  | 2022-06-08 03:30:32,167 INFO [network.oxalis.commons.settings.SettingsBuilder] Tracing => TRACER: noop
0|EHF service  | 2022-06-08 03:30:32,167 INFO [network.oxalis.commons.settings.SettingsBuilder] Executor => DEFAULT: 50
0|EHF service  | 2022-06-08 03:30:32,167 INFO [network.oxalis.commons.settings.SettingsBuilder] Executor => STATISTICS: 50
0|EHF service  | 2022-06-08 03:30:32,167 INFO [network.oxalis.commons.settings.SettingsBuilder] Tag => GENERATOR: noop
0|EHF service  | 2022-06-08 03:30:32,168 INFO [network.oxalis.commons.settings.SettingsBuilder] Timestamp => SERVICE: system
0|EHF service  | 2022-06-08 03:30:32,168 INFO [network.oxalis.commons.settings.SettingsBuilder] Evidence => SERVICE: rem
0|EHF service  | 2022-06-08 03:30:32,168 INFO [network.oxalis.commons.settings.SettingsBuilder] Transformer => DETECTOR: noop
0|EHF service  | 2022-06-08 03:30:32,168 INFO [network.oxalis.commons.settings.SettingsBuilder] Transformer => WRAPPER: xml
0|EHF service  | 2022-06-08 03:30:32,168 INFO [network.oxalis.commons.settings.SettingsBuilder] Statistics => SERVICE: noop
0|EHF service  | 2022-06-08 03:30:32,168 INFO [network.oxalis.commons.settings.SettingsBuilder] Transmission => VERIFIER: default
0|EHF service  | 2022-06-08 03:30:32,169 INFO [network.oxalis.commons.settings.SettingsBuilder] AS4 => HOSTNAME:
0|EHF service  | 2022-06-08 03:30:32,169 INFO [network.oxalis.commons.settings.SettingsBuilder] AS4 => MSGID_GENERATOR: default
0|EHF service  | 2022-06-08 03:30:32,169 INFO [network.oxalis.commons.settings.SettingsBuilder] AS4 => TYPE: peppol
0|EHF service  | 2022-06-08 03:30:32,169 INFO [network.oxalis.commons.settings.SettingsBuilder] Logging => CONFIG: <null>
0|EHF service  | 2022-06-08 03:30:32,169 INFO [network.oxalis.commons.settings.SettingsBuilder] Logging => SERVICE: logback
0|EHF service  | 2022-06-08 03:30:32,279 INFO [network.oxalis.commons.security.CertificateModule] Certificate subject: CN=PNO000318, OU=PEPPOL PRODUCTION AP, O=Oryton AS, C=NO
0|EHF service  | 2022-06-08 03:30:32,279 INFO [network.oxalis.commons.security.CertificateModule] Certificate issuer: CN=PEPPOL ACCESS POINT CA - G2, O=OpenPEPPOL AISBL, C=BE
0|EHF service  | 2022-06-08 03:30:32,443 INFO [network.oxalis.vefa.peppol.security.ModeDetector] Detection error (TEST): Validation of subject principal(CN) failed.
0|EHF service  | 2022-06-08 03:30:32,447 INFO [network.oxalis.vefa.peppol.security.ModeDetector] Detection error (LOCAL): Certificate should be self-signed.
0|EHF service  | 2022-06-08 03:30:33,144 INFO [network.oxalis.vefa.peppol.security.ModeDetector] Detected mode: PRODUCTION
0|EHF service  | 2022-06-08 03:30:33,153 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] Prioritized list of transport profiles:
0|EHF service  | 2022-06-08 03:30:33,153 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => peppol-transport-as4-v2_0
0|EHF service  | 2022-06-08 03:30:33,153 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => bdxr-transport-ebms3-as4-v1p0
0|EHF service  | 2022-06-08 03:30:33,153 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1
0|EHF service  | 2022-06-08 03:30:33,153 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver2p0
0|EHF service  | 2022-06-08 03:30:33,153 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0
0|EHF service  | 2022-06-08 03:30:34,862 WARN [org.apache.cxf.ws.policy.AssertionBuilderRegistryImpl] No assertion builder for type {http://oxalis.network/custom/security-policy}Basic128GCMSha256MgfSha256 registered.
0|EHF service  | 3d8c39d5-c21c-4962-bb40-95688cc56741@EHFAndBankSftponly transmission took 2039 ms
0|EHF service  | Average transmission time was 2039.0ms
0|EHF service  | Total time spent: 3s
0|EHF service  | Attempted to send 1 files
0|EHF service  | Failed transmissions: 0
0|EHF service  | Transmission speed 0 documents per second

I am using this java cmd to send
java -cp "/opt/oxalis/oxalis-standalone-as4/standalone/bin/*:/opt/oxalis/oxalis-standalone-as4/as4/*" eu.sendregning.oxalis.Main \
        -f ehfFilePath \
        -e outputFolderPath \
        -cert /opt/tomcat9/.oxalis/2021/cert.cer \
        --protocol peppol-transport-as4-v2_0 \
        -r 0192:xxxxxxxxxx \
        -s 0192:xxxxxxxxxx

Do we still miss any configs ?

**Comment by tranthanhtam8890** [comment]
@aaron-kumar  Thank you, issue has been resolve after remove overide. Can close this ticket now :)
