### ISSUE TITLE
Transport profile on inbound messages

### ISSUE THREAD

**Issue by emilbokenstrand** [OxalisCommunity/oxalis#638]
For the Peppol Transaction Statistics Reporting we need the transport profile that being used. All our participants are set up with profile 'peppol-transport-as4-v2_0' but when I want to extract the transport profile for inbound messages I always get 'bdxr-transport-ebms3-as4-v1p0'.

I use the following code upon receiving a file when trying to extract it: 
network.oxalis.api.inbound.InboundMetadata.getProtocol and my oxalis version is 6.1.1

Am I doing something wrong?

**Comment by aaron-kumar** [comment]
Fixed with commit https://github.com/OxalisCommunity/oxalis/commit/a4aa9466070e33afc4e1fdd491cbdbf037c01066

**Comment by nkoudelia** [comment]
@aaron-kumar I'm using [norstella/oxalis-as4:6.4.0](https://hub.docker.com/layers/norstella/oxalis-as4/6.4.0/images/sha256-81906e968986011a708392805d29c24e17e48055f2967cf744cf72c31a7144c3?context=explore) but the [StatisticsService](https://github.com/OxalisCommunity/oxalis/blob/master/oxalis-api/src/main/java/network/oxalis/api/statistics/StatisticsService.java) plugin is still reporting all incoming messages to use `bdxr-transport-ebms3-as4-v1p0`. Is there something wrong?
