### ISSUE TITLE
FAIL Start Oxalis From Tomcat

### ISSUE THREAD

**Issue by DioMeo** [OxalisCommunity/oxalis#644]
Hello everyone, when I try to start my Oxalis application, for the status check, from Tomcat Manager it gives me the following error

"Application at context path [/oxalis] could not be started"

this my oxalis.conf: 

oxalis.keystore: {
    path: name_cert_test.jks
    password: pwd_cert

    key: {
        alias: alias_cert
        password: pwd_alias_cert
    }
}

Any idea?
What am I doing wrong?

It is a new installation, so the release is 6.3.0.

Thanks for support :)

**Comment by DioMeo** [comment]
this is my catalina log:
24-Nov-2023 11:33:40.074 INFO [main] org.apache.catalina.core.StandardServer.await A valid shutdown command was received via the shutdown port. Stopping the Server instance.
24-Nov-2023 11:33:40.074 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8080"]
24-Nov-2023 11:33:40.078 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["ajp-nio-0:0:0:0:0:0:0:1-8009"]
24-Nov-2023 11:33:40.078 INFO [main] org.apache.catalina.core.StandardService.stopInternal Stopping service [Catalina]
24-Nov-2023 11:33:40.178 INFO [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-8080"]
24-Nov-2023 11:33:40.189 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8080"]
24-Nov-2023 11:33:40.189 INFO [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["ajp-nio-0:0:0:0:0:0:0:1-8009"]
24-Nov-2023 11:33:40.190 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["ajp-nio-0:0:0:0:0:0:0:1-8009"]
24-Nov-2023 11:33:41.510 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.82
24-Nov-2023 11:33:41.512 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Oct 11 2023 13:15:08 UTC
24-Nov-2023 11:33:41.512 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.82.0
24-Nov-2023 11:33:41.512 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
24-Nov-2023 11:33:41.513 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.15.0-89-generic
24-Nov-2023 11:33:41.513 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
24-Nov-2023 11:33:41.513 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-11-openjdk-amd64
24-Nov-2023 11:33:41.513 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.20.1+1-post-Ubuntu-0ubuntu122.04
24-Nov-2023 11:33:41.513 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Ubuntu
24-Nov-2023 11:33:41.513 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /opt/tomcat
24-Nov-2023 11:33:41.513 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /opt/tomcat
24-Nov-2023 11:33:41.524 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
24-Nov-2023 11:33:41.524 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
24-Nov-2023 11:33:41.525 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
24-Nov-2023 11:33:41.525 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
24-Nov-2023 11:33:41.525 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
24-Nov-2023 11:33:41.525 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/opt/tomcat/conf/logging.properties
24-Nov-2023 11:33:41.525 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
24-Nov-2023 11:33:41.525 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.security.egd=file:///dev/urandom
24-Nov-2023 11:33:41.526 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
24-Nov-2023 11:33:41.526 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
24-Nov-2023 11:33:41.526 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
24-Nov-2023 11:33:41.526 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
24-Nov-2023 11:33:41.526 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms512M
24-Nov-2023 11:33:41.526 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx1024M
24-Nov-2023 11:33:41.526 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseParallelGC
24-Nov-2023 11:33:41.527 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
24-Nov-2023 11:33:41.527 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/opt/tomcat
24-Nov-2023 11:33:41.527 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/opt/tomcat
24-Nov-2023 11:33:41.527 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/opt/tomcat/temp
24-Nov-2023 11:33:41.532 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib]
24-Nov-2023 11:33:41.873 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
24-Nov-2023 11:33:41.900 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-0:0:0:0:0:0:0:1-8009"]
24-Nov-2023 11:33:41.907 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [557] milliseconds
24-Nov-2023 11:33:41.992 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
24-Nov-2023 11:33:41.992 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.82]
24-Nov-2023 11:33:42.010 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/opt/tomcat/webapps/oxalis.war]
24-Nov-2023 11:33:44.823 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
24-Nov-2023 11:33:44.828 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/oxalis] startup failed due to previous errors
24-Nov-2023 11:33:44.844 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/opt/tomcat/webapps/oxalis.war] has finished in [2,834] ms
24-Nov-2023 11:33:44.845 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/examples]
24-Nov-2023 11:33:45.042 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/examples] has finished in [197] ms
24-Nov-2023 11:33:45.043 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/manager]
24-Nov-2023 11:33:45.076 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/manager] has finished in [33] ms
24-Nov-2023 11:33:45.076 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/docs]
24-Nov-2023 11:33:45.094 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/docs] has finished in [17] ms
24-Nov-2023 11:33:45.094 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/host-manager]
24-Nov-2023 11:33:45.113 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/host-manager] has finished in [19] ms
24-Nov-2023 11:33:45.114 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/ROOT]
24-Nov-2023 11:33:45.132 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/ROOT] has finished in [17] ms
24-Nov-2023 11:33:45.140 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
24-Nov-2023 11:33:45.160 SEVERE [main] org.apache.catalina.util.LifecycleBase.handleSubClassException Failed to start component [Connector["ajp-nio-0:0:0:0:0:0:0:1-8009"]]
        org.apache.catalina.LifecycleException: Protocol handler start failed
                at org.apache.catalina.connector.Connector.startInternal(Connector.java:1042)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
                at org.apache.catalina.core.StandardService.startInternal(StandardService.java:450)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
                at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:921)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
        Caused by: java.lang.IllegalArgumentException: The AJP Connector is configured with secretRequired="true" but the secret attribute is either null or "". This combination is not valid.
                at org.apache.coyote.ajp.AbstractAjpProtocol.start(AbstractAjpProtocol.java:277)
                at org.apache.catalina.connector.Connector.startInternal(Connector.java:1039)

**Comment by OysteinLq** [comment]
You don't give much context here, but you  might want to consider the second solution offered here: https://stackoverflow.com/questions/60501470/the-ajp-connector-is-configured-with-secretrequired-true-but-the-secret-attrib 

I would guess this isn't an issue with using Oxalis itself, but as we don't run it with Tomcat at our company, I couldn't say for sure -- looks like a proxy issue. Does starting the Tomcat without Oxalis deployed work?

**Comment by DioMeo** [comment]
Hello OysteinLq, and thanks to reply me.
The problem was the double quotas missing in my oxalis.conf, for pwds and key.cert.
