### ISSUE TITLE
Issue installing Oxalis AS4-6.3.0

### ISSUE THREAD

**Issue by DioMeo** [OxalisCommunity/oxalis#645]
Hi,
I've installed with success Oxalis 6.3.0 on Tomcat8+ using the oxalis-war-6.3.0.war file released, for a Linux server.

Following the README.txt file for AS4, I've created the "ext" folder in the /opt/tomcat/webapps/oxalis/WEB-INF folder and put all the jars extracted from the oxalis-as4-6.3.0-dist.zip.

Also I've created the oxalis.xml file in the Catalina/localhost folder (I hope is correct write in this way)
[oxalis.txt](https://github.com/OxalisCommunity/oxalis/files/13460722/oxalis.txt)

and restarted tomcat service.
But no way to see the localhost:8080/as4 endpoint.

So, I've copied the .jar files into the .../WEB-INF/lib, that contain the as2 files, and restarted tomcat service but the Oxalis site goes in 404 not found.

Could you please give me help on this problem?
Thank you and regards!

**Comment by DioMeo** [comment]
<?xml version="1.0" encoding="UTF-8"?>








<Context docBase="/opt/tomcat/webapps/oxalis.war"  >
    
   
   <Environment name="OXALIS_HOME" value="/opt/tomcat/.oxalis" type="java.lang.String" override="false" />

    
   
   <Resources className="org.apache.catalina.webresources.ExtractingRoot">
            
      
       
      
      
      <PostResources
        base="/opt/tomcat/webapps/oxalis/WEB-INF/as4" 
        className="org.apache.catalina.webresources.DirResourceSet"
        webAppMount="/opt/tomcat/webapps/oxalis/WEB-INF/lib"
        />  
      
      
      
      
      
   </Resources>

</Context>

**Comment by RichardVanMaaren** [comment]
Did you also try oxalis/as4 ? What do the tomcat logs tell you ?

Best regards,

**Comment by aaron-kumar** [comment]
Try with attached [oxalis.xml.txt](https://github.com/OxalisCommunity/oxalis/files/13472383/oxalis.xml.txt) - Remove .txt extension. 
Place it in TOMCAT_INSTALL-DIR/conf/Catalina/localhost. Check/correct the path for Oxalis and Oxalis-AS4 distribution. 


Following are the URLs (if context file name is "oxalis.xml"):
- http://localhost:8080/oxalis/as4
- http://localhost:8080/oxalis/status

Note that there are multiple way to integrate Oxalis with your backend system.

**Comment by DioMeo** [comment]
Hello, I solved the problem, caused by the permissions for that file.
Setting 0750, worked.
Thanks to reply me.
