### ISSUE TITLE
Tests failing on current (25a4a2b) master branch - "Identifier '0208:0871221633' is not registered in SML"

### ISSUE THREAD

**Issue by fairartursolups** [OxalisCommunity/oxalis#659]
Hei, hei!

Seems like on January 1st some code rot managed to creep into the project.

Currently, when trying to run `mvn clean test` on master branch (25a4a2b) all test cases that are using identifier `0208:0871221633` are failing.

This seems to be caused by decommission of [smp.belgium.be](https://smp.belgium.be) in which aforementioned identifier's metadata resided.

![Screenshot 2024-01-04 at 16 05 53](https://github.com/OxalisCommunity/oxalis/assets/146727898/ffb66fd6-945c-4201-a4a2-3473d62a0992)

**Comment by fairartursolups** [comment]
In addition, maybe it is time to change the transport type on the test cases from as2 to as4. :)

**Comment by aaron-kumar** [comment]
@fairartursolups : Thanks for reporting. We are aware of issue. In addition to Belgium SMP ([smp.belgium.be](https://smp.belgium.be/)) specific thing, all Peppol SMP stopped registering "AS2" protocol in SMP. 

We are already working on new Oxalis version, where we are Not only removing AS2 protocol but also merging "[Oxalis-AS4](https://github.com/OxalisCommunity/Oxalis-AS4)" with "[Oxalis](https://github.com/OxalisCommunity/oxalis)". This was already communicated in last [Technical Meeting in December 2023](https://www.oxalis.network/tech-dialog-meeting-131223). 

P.S. We recommend you to use released version of Oxalis, but somehow if you want to run master for certain reason then you can comment those tests for time being until we release new major version.

**Comment by aaron-kumar** [comment]
@fairartursolups : test-cases fixed as part of commit https://github.com/OxalisCommunity/oxalis/commit/2125e3b7340597b862f5713e54b3af090e0bbbc1.
