### ISSUE TITLE
Peppol reporting & C2SeatID for incoming message

### ISSUE THREAD

**Issue by nkoudelia** [OxalisCommunity/oxalis#664]
I'm working on gathering TSR data for the [Peppol report](https://github.com/OxalisCommunity/oxalis/wiki/Peppol-Reporting-%E2%80%90-WIP) and there is one piece of information I can't find, namely this:

![image](https://github.com/OxalisCommunity/oxalis/assets/91388229/dd942b92-c751-47f5-adab-eec8c74f25e7)

I need to get **C2SeatID** for _incoming_ transaction but the receipt made from incoming transaction contains the receiver's (C3), not the sender's (C2) certificate.

EDIT: figured it out - the certificate I am seeing in the message receipt is my own signature. It's unrelated to the sender certificate.

**Comment by dladlk** [comment]
Hello @nkoudelia , may I ask you how you solved this C2SeatID for incoming messages? 
As far as I see it in the code, neither provided implementations of EvidenceFactory (RemEvidenceFactory or PrimaryEvidenceFactory) serialize a sender certificate from As4InboundMetadata (implementation of TransmissionResult) - so you need to expand it with your own implementation of network.oxalis.api.persist.ReceiptPersister and configure it via `oxalis.persister.receipt=yourimpl`
