### ISSUE TITLE
The library vefa-peppol causes Oxalis to incorrectly report network-level errors as participant not found

### ISSUE THREAD

**Issue by steinarhenriksen** [OxalisCommunity/oxalis#666]
The library vefa-peppol causes Oxalis to incorrectly report network-level errors as participant not found.

I just reported a issue to the vefa-peppol project at https://github.com/OxalisCommunity/vefa-peppol/issues/56

Oxalis will need to update the version of vefa-peppol being used after the issue has been resolved there.

The issue is somewhat related to another open issue in that they both deal with exception handling. See https://github.com/OxalisCommunity/oxalis/issues/586

**Comment by aaron-kumar** [comment]
Fixed with release https://github.com/OxalisCommunity/oxalis/releases/tag/v6.7.0
