### ISSUE TITLE
Peppol reporting - Content does not contain SBDH

### ISSUE THREAD

**Issue by tinhien11** [OxalisCommunity/oxalis#697]
Hi. I am trying out the TestBed.
I can successfully run Oxalis for message reception and submission. However, I am facing issues with message submission reporting for AS4.

version.oxalis.as4: 6.7.0
version.java: 11.0.16
mode: TEST

Payload:
`<?xml version="1.0" encoding="UTF-8"?>
<StandardBusinessDocument xmlns="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader">
    <StandardBusinessDocumentHeader>
        <HeaderVersion>1.0</HeaderVersion>
        <Sender>
            <Identifier Authority="iso6523-actorid-upis">9922:tin</Identifier>
        </Sender>
        <Receiver>
            <Identifier Authority="iso6523-actorid-upis">9922:NGTBCNTRLP1001</Identifier>
        </Receiver>
        <DocumentIdentification>
            <Standard>urn:fdc:peppol:end-user-statistics-report:1.1::EndUserStatisticsReport</Standard>
            <TypeVersion>1.1</TypeVersion>
            <InstanceIdentifier>PSG000680-80-20241108T033715</InstanceIdentifier>
            <Type>EndUserStatisticsReport</Type>
            <CreationDateAndTime>2024-08-19T08:13:49.821Z</CreationDateAndTime>
        </DocumentIdentification>
        <BusinessScope>
            <Scope>
                <Type>COUNTRY_C1</Type>
                <InstanceIdentifier>BE</InstanceIdentifier>
            </Scope>
        </BusinessScope>
    </StandardBusinessDocumentHeader>
    <EndUserStatisticsReport xmlns="urn:fdc:peppol:end-user-statistics-report:1.1">
        <CustomizationID>urn:fdc:peppol.eu:edec:trns:end-user-statistics-report:1.1</CustomizationID>
        <ProfileID>urn:fdc:peppol.eu:edec:bis:reporting:1.0</ProfileID>
        <Header>
            <ReportPeriod>
                <StartDate>2022-01-01</StartDate>
                <EndDate>2022-01-31</EndDate>
            </ReportPeriod>
            <ReporterID schemeID="CertSubjectCN">POP000360</ReporterID>
        </Header>
        <FullSet>
            <SendingEndUsers>0</SendingEndUsers>
            <ReceivingEndUsers>0</ReceivingEndUsers>
            <SendingOrReceivingEndUsers>0</SendingOrReceivingEndUsers>
        </FullSet>
    </EndUserStatisticsReport>
</StandardBusinessDocument>`

Response:
Message failed : Content does not contain SBDH.

Any pointers on what I should check? Thanks so much

**Comment by aaron-kumar** [comment]
@tinhien11  Mandatory Process ID (PROCESSID) and Document Type ID (DOCUMENTID) scope are missing in SBDH. 

```
StandardBusinessDocument/StandardBusinessDocumentHeader/BusinessScope/Scope/Type
StandardBusinessDocument/StandardBusinessDocumentHeader/BusinessScope/Scope/InstanceIdentifier
StandardBusinessDocument/StandardBusinessDocumentHeader/BusinessScope/Scope/Identifier
```
Example:
```
			<Scope>
				<Type>DOCUMENTID</Type>
				<InstanceIdentifier>urn:fdc:peppol:end-user-statistics-report:1.1::EndUserStatisticsReport##urn:fdc:peppol.eu:edec:trns:end-user-statistics-report:1.1::1.1</InstanceIdentifier>
				<Identifier>busdox-docid-qns</Identifier>
			</Scope>
			<Scope>
				<Type>PROCESSID</Type>
				<InstanceIdentifier>urn:fdc:peppol.eu:edec:bis:reporting:1.0</InstanceIdentifier>
				<Identifier>cenbii-procid-ubl</Identifier>
			</Scope>
```

**Comment by tinhien11** [comment]
It works perfectly. Thank you very much!

**Comment by eyop23** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<SignalMessage xmlns="http://peppol.eu/2017/sbdh">
    <Header>
        <MessageId>uuid:12345678-abcd-efgh-ijkl-1234567890ab</MessageId>
        <Sender>
            <Identifier scheme="peppol">9908:987654321</Identifier>
        </Sender>
        <Receiver>
            <Identifier scheme="peppol">9908:123456789</Identifier>
        </Receiver>
        <Timestamp>2024-12-08T12:00:00Z</Timestamp>
    </Header>
    <Payload>
        <Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2">
            <ID>INV-12345</ID>
            <IssueDate>2024-12-08</IssueDate>
            <InvoiceTypeCode>380</InvoiceTypeCode> 
            <AccountingSupplierParty>
                <Party>
                    <PartyIdentification>
                        <ID schemeID="9908">987654321</ID>
                    </PartyIdentification>
                    <PartyName>
                        <Name>Supplier Company Name</Name>
                    </PartyName>
                </Party>
            </AccountingSupplierParty>
            <AccountingCustomerParty>
                <Party>
                    <PartyIdentification>
                        <ID schemeID="9908">123456789</ID>
                    </PartyIdentification>
                    <PartyName>
                        <Name>Customer Company Name</Name>
                    </PartyName>
                </Party>
            </AccountingCustomerParty>
            <InvoiceLine>
                <ID>1</ID>
                <InvoicedQuantity unitCode="C62">1</InvoicedQuantity>
                <LineExtensionAmount currencyID="EUR">100.00</LineExtensionAmount>
                <Item>
                    <Name>Product/Service Description</Name>
                    <ClassifiedTaxCategory>
                        <TaxScheme>
                            <ID>VAT</ID>
                        </TaxScheme>
                    </ClassifiedTaxCategory>
                </Item>
                <Price>
                    <PriceAmount currencyID="EUR">100.00</PriceAmount>
                </Price>
            </InvoiceLine>
            <LegalMonetaryTotal>
                <PayableAmount currencyID="EUR">100.00</PayableAmount>
            </LegalMonetaryTotal>
        </Invoice>
    </Payload>
</SignalMessage>
when i say
~/Desktop/ap/oxalis$ java -jar ~/Desktop/ap/oxalis/oxalis-standalone.jar     -f /home/cool/Desktop/ap/oxalis/invoice.xml     -r 9908:987654321     -s 9908:123456789     -c TEST
got this error

Message failed : Content does not contain SBDH.

2024-12-08 14:52:40,710 ERROR [eu.sendregning.oxalis.Main] Execution failed: network.oxalis.api.lang.OxalisTransmissionException: No transmission is provided. 
java.util.concurrent.ExecutionException: network.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at eu.sendregning.oxalis.Main.main(Main.java:228)
Caused by: network.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at network.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:106)
        at network.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:96)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:157)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:90)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:52)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Total time spent: 0s
Attempted to send 0 files
Failed transmissions: 1
